version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-node-browsers

    steps:
      - checkout
      - run:
          name: Install required libraries
          command: |
            sudo apt-get install -y libzip-dev
            sudo docker-php-ext-install zip pcntl
      - run:
          name: Install dependencies
          command: |
            sudo composer self-update
            composer install -n --prefer-dist
      - run:
          name: Syntax tests
          command: |
            wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer
            chmod a+x php-cs-fixer
            ./php-cs-fixer fix --dry-run
      - run:
          name: Unit tests
          command: php bin/phpunit
      - run:
          name: E2E tests
          command: |
            git clone https://github.com/contentful/the-example-app-e2e-tests.git ./tests-e2e
            cd tests-e2e
            npm install
            cd ..
            php bin/console server:start 127.0.0.1:8000
            ./tests-e2e/node_modules/.bin/cypress run
